---
abstract: 'Perl implementation of the GNU Classpath LinkedList.'
author:
  - 'Lloyd Griffiths (lloydg@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-LinkedList
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.26
  Iterator::Util: 0.02
  Storable: 2.34
  Test::Exception: 0.31
  Test::Simple: 0.98
resources:
  repository: https://github.com/LloydGriffiths/Data-LinkedList
version: 0.01
